disabled_rules:
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - identifier_name
  - large_tuple
  - nesting
  - notification_center_detachment
  - type_body_length
  - multiline_arguments
  - trailing_closure
  - type_name
opt_in_rules:
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - first_where
  - joined_default_parameter
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - sorted_imports
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
line_length:
  warning: 140
statement_position:
  uncuddled_else: true
trailing_comma:
  mandatory_comma: true
custom_rules:
  no_empty_line_after_func:
    name: "No Empty Line After Function"
    regex: '(^ *(func|init)[ a-zA-Z0-9=?.\(\),><!:\[\]\-]*\{$\s^$)'
    message: "There should not be an empty line after a function definition"
    severity: warning